name: Deploy to iGEM

on:
  push:
    branches:
      - main
      - dev
      - dev-kyle
      - dev-cam
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'iGEM'
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Template Site
        run: python igem_site_builder template 'temp\\build' 'src'

      - name: Apply Post Processing
        run: python igem_site_builder post-process 'temp\\build' 'src'
        
      - name: Deploy to iGEM MediaWiki Server
        env:
            IGEM_USERNAME: ${{secrets.IGEM_USERNAME}}
            IGEM_PASSWORD: ${{secrets.IGEM_PASSWORD}}
        run: python igem_site_builder sync 'temp\\build' 'temp\\sync' '${{secrets.IGEM_TEAM_NAME}}'
          
